// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.4;

/**
 * @title ISushiV2Factory
 * @notice Interface for Sushi's V2 Factory
 * @dev Factory for creating SushiSwap V2 pools
 * @custom:katana 0x72d111b4d6f31b38919ae39779f570b747d6acd9
 * @custom:tatara 0xb45e53277a7e0f1d35f2a77160e91e25507f1763
 * @custom:tags sushi,swap,dex,defi,v2
 */
interface ISushiV2Factory {
    event PairCreated(
        address indexed token0,
        address indexed token1,
        address pair,
        uint256
    );

    function allPairs(uint256) external view returns (address);

    function allPairsLength() external view returns (uint256);

    function createPair(address tokenA, address tokenB)
        external
        returns (address pair);

    function feeTo() external view returns (address);

    function feeToSetter() external view returns (address);

    function getPair(address, address) external view returns (address);

    function migrator() external view returns (address);

    function pairCodeHash() external pure returns (bytes32);

    function setFeeTo(address _feeTo) external;

    function setFeeToSetter(address _feeToSetter) external;

    function setMigrator(address _migrator) external;
}